<?php

namespace DoctrineORMModule\Proxy\__CG__\Music\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Artist extends \Music\Entity\Artist implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getWebsite()
    {
        $this->__load();
        return parent::getWebsite();
    }

    public function getGenres()
    {
        $this->__load();
        return parent::getGenres();
    }

    public function getAlbums()
    {
        $this->__load();
        return parent::getAlbums();
    }

    public function getSongs()
    {
        $this->__load();
        return parent::getSongs();
    }

    public function setName($name = '')
    {
        $this->__load();
        return parent::setName($name);
    }

    public function setEmail($email = '')
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function setWebsite($website = '')
    {
        $this->__load();
        return parent::setWebsite($website);
    }

    public function setGenres($genres = array (
))
    {
        $this->__load();
        return parent::setGenres($genres);
    }

    public function addGenre(\Music\Entity\Genre $genre)
    {
        $this->__load();
        return parent::addGenre($genre);
    }

    public function addAlbum($album = '')
    {
        $this->__load();
        return parent::addAlbum($album);
    }

    public function addSong($song = '')
    {
        $this->__load();
        return parent::addSong($song);
    }

    public function removeGenre(\Music\Entity\Genre $genre)
    {
        $this->__load();
        return parent::removeGenre($genre);
    }

    public function getArrayCopy()
    {
        $this->__load();
        return parent::getArrayCopy();
    }

    public function populate($data = array (
))
    {
        $this->__load();
        return parent::populate($data);
    }

    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {
        $this->__load();
        return parent::setInputFilter($inputFilter);
    }

    public function getInputFilter()
    {
        $this->__load();
        return parent::getInputFilter();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'email', 'website', 'genres', 'albums');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}