<?php
    $title = 'Add Genre';
    $this->headTitle($title);
?>
<h2><?php echo $title; ?></h2>

<?php
$form->setAttribute('action', $this->url('genre', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('csrf')) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formRow($form->get('name')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;
?>
