<?php
$title = 'Genres';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<table border="0" width="100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th><a href="<?php echo $this->url('genre', array('action' => 'add')); ?>" title="Add a genre.">Add +</a></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($genres as $genre): ?>
        <tr>
            <td><?php echo (int) $genre->getId(); ?></td>
            <td>
                <a href="<?php echo $this->url('genre', array('action' => 'view', 'id' => (int) $genre->getId())); ?>">
                <?php echo $this->escapeHtml($genre->getName()); ?>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url('genre', array('action' => 'edit', 'id' => (int) $genre->getId())); ?>"
                   class="label primary small round"
                   title="Edit Genre <?php echo (int) $genre->getId(); ?>">Edit</a>
                &nbsp;
                <a href="<?php echo $this->url('genre', array('action' => 'delete', 'id' => (int) $genre->getId())); ?>"
                   class="label alert small round"
                   title="Edit Genre <?php echo (int) $genre->getId(); ?>">Delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>





