<?php
$title = $this->escapeHtml($genre->getName());
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<h3>Artists</h3>

<table border="0" width="100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>
                <a
                    href="<?php echo $this->url('artist', array('action' => 'add')); ?>"
                    title="Add an artist.">Add +
                </a>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($artists as $artist): ?>
        <tr>
            <td><?php echo (int) $artist->getId(); ?></td>
            <td>
                <a href="<?php echo $this->url('artist', array('action' => 'view', 'id' => (int) $artist->getId())); ?>">
                    <?php echo $this->escapeHtml($artist->getName()); ?>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url('artist', array('action' => 'edit', 'id' => (int) $artist->getId())); ?>"
                   class="label primary small round"
                   title="Edit artist <?php echo (int) $artist->getId(); ?>.">Edit</a>
                &nbsp;
                <a href="<?php echo $this->url('artist', array('action' => 'delete', 'id' => (int) $artist->getId())); ?>"
                   class="label alert small round"
                   title="Delete artist <?php echo (int) $artist->getId(); ?>.">Delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
